import React, { useState } from "react";
import "../index.css";

const LandingPage = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedFile, setSelectedFile] = useState(null);

  const handleFileChange = (e) => {
    setSelectedFile(e.target.files[0]);
  };

  const handleUpload = () => {
    if (!selectedFile) {
      alert("Please select a file!");
      return;
    }
    console.log("Uploading:", selectedFile.name);
    // You can integrate the upload API here
  };

  return (
    <div className="w-screen min-h-screen">
      {/* Navbar */}
      <nav className="w-full flex justify-between items-center px-8 py-4 shadow-md bg-[#edf8fc]">
        <div className="text-2xl font-semibold text-gray-700">
          mediseek.<span className="text-gray-500">ai</span>
        </div>
        <div className="hidden md:flex space-x-6 text-gray-600">
          {["Home", "Enterprise", "Products", "About", "Blog", "Careers"].map((item) => (
            <a
              key={item}
              href="#"
              className="px-4 py-2 hover:underline hover:border-2 rounded-xl border-gray-800"
            >
              {item}
            </a>
          ))}
        </div>

        <button className="bg-teal-400 text-black px-4 py-2 rounded-lg hover:bg-teal-500">
          Free Trial
        </button>
      </nav>

      {/* Hero Section */}
      <div className="flex flex-col md:flex-row items-center justify-evenly text-center md:text-left py-20 px-6 w-screen bg-gradient-to-b from-[#bce1f1] to-white">
        {/* Left Side - Text */}
        <div className="md:w-1/2 ml-52 mr-[-50px] flex flex-col items-center md:items-start">
          <h1 className="text-5xl font-semibold text-gray-800 w-full">
            Empower your Patients with the Best Technology
          </h1>
          <div className="w-[500px] m-2 ml-10 border-b-2 border-gray-500 my-4"></div>
          <p className="text-gray-700 text-lg w-full max-w-lg">
            Smart Reports processes <span className="font-bold">diagnostic lab test reports</span>, and
            <span className="font-bold"> translates patients’ health and biomarker values</span>
            into easily-understood clinical readings, health tips, and other insights generated by an AI-based medical reasoning engine.
          </p>
          <button
            onClick={() => setIsModalOpen(true)}
            className="mt-6 bg-red-600 text-black border-2 border-gray-400 px-6 py-3 rounded-lg text-lg hover:bg-indigo-700"
          >
            Scan Your Report ⮞
          </button>
        </div>

        {/* Right Side - Image */}
        <div className="md:w-1/2 flex justify-center items-center">
          <img src="/main.png" alt="Smart Reports Preview" className="w-full max-w-md rounded-lg" />
        </div>
      </div>

      {/* Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white p-6 rounded-lg shadow-lg w-[400px]">
            <h2 className="text-xl font-semibold text-gray-700 mb-4">Upload Your Report</h2>

            {/* File Upload Input */}
            <input type="file" onChange={handleFileChange} className="mb-4 border p-2 w-full" />

            {/* Buttons */}
            <div className="flex justify-end space-x-3">
              <button
                onClick={handleUpload}
                className="bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-green-600"
              >
                Upload
              </button>
              <button
                onClick={() => setIsModalOpen(false)}
                className="bg-gray-500 text-white px-4 py-2 rounded-lg hover:bg-gray-600"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default LandingPage;
